config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "landing#index"
  post "/" => "landing#index", as: "landing"
  get "/show/:id" => "landing#show", as: :show_product

  namespace :admin do
    root to: "dashboard#index"
    get "profiles/edit"
    patch "profiles/update"
    get "profiles/:username", to: "profiles#show", as: "public_profile"
    get "users/search", to: "users#search"
    get "products/search", to: "products#search"
    resources :invoices, except: [ :edit, :update ] do
      member do
        patch :cancel
      end
    end
    resources :users do
      member do
        post :block
        post :activate
      end
    end
    namespace :products do
      resources :categories, except: :show
    end
    resources :products do
      member do
        get :update_stock
        patch :update_stock
        post :publish
        post :hide
        get :add_images
        delete :destroy_image
      end
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [ :create, :new ]
  resource :session, controller: "clearance/sessions", only: [ :create ]

  resources :users, controller: "clearance/users", only: [ :create ] do
    resource :password,
      controller: "clearance/passwords",
      only: [ :edit, :update ]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"

  # scope module: "storefront" do
  # end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :set_categories
  def index
    @products = Product.published_products.order(created_at: :desc)
    if params[:category]
      @category = Product::Category.find(params[:category])
      @products = @category.products
    end
    @products = @products.by_name_or_description(params[:query]) if params[:query]
    @pagy, @products = pagy(@products)
    respond_to do |format|
      format.html # GET
      format.turbo_stream # POST
    end
  end
  def show
    @product = Product.find(params[:id])
  end

  private
  def set_categories
    @categories = Product::Category.all
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/_product.html.erb
<div id="<%= dom_id product %>" class="card lg:card-side bg-base-100 shadow">
  <div class="card-body">
    <h2 class="card-title"><%= product.name %></h2>
    <p><%= product.description %></p>
    <p>Price: <%= number_to_currency(product.base_price) %></p>
    <p>Stock: <%= product.stock_quantity %></p>
  </div>

  <figure class="card-figure max-w-md">
    <%= image_tag product_image_url(product), class: "" %>
  </figure>
</div>

app/views/landing/_product_mini.html.erb
<div id="<%= dom_id product %>" class="card bg-base-neutral max-w-sm shadow border border-1 rounded-lg">
  <figure class="card-figure mx-auto">
    <%= image_tag product_image_url(product), class: "" %>
  </figure>
  <div class="card-body">
    <h2 class="card-title"><%= product.name %></h2>
    <p><%= number_to_currency(product.base_price) %></p>
    <%= link_to "Ver", show_product_path(product), class: "btn btn-outline w-full mt-4" %>
  </div>

</div>

app/views/landing/_products.turbo_stream.erb
<%= turbo_stream.append "products" do %>
  <%= render partial: "product_mini", collection: @products, as: :product %>
<% end %>
<%= turbo_stream.update "next_link" do %>
  <% if @pagy.next.present? %>
    <%= button_to "next", pagy_url_for(@pagy, @pagy.next) %>
  <% end %>
<% end %>

app/views/landing/index.html.erb
<% content_for :title do %>
  Avivas - Sport Clothing Store
<% end %>

<% content_for :header do %>
  <%= render "shared/navbar" %>
<% end %>

<section class="hero bg-base-100 mt-4 min-h-screen md:-mt-[7rem]">
  <div class="hero-content">
    <div class="max-w-screen-xl mx-auto text-center">
      <h1 class="font-bold text-[4rem] mx-auto">
        Ropa simple, vida compleja
        <span>
          <svg class="w-full max-w-44 h-auto" width="1994" height="253" viewBox="0 0 1994 253" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M38 215C369.5 38 889 38 889 38C889 38 1608.5 38 1956.5 215" stroke="#FFCE00" stroke-width="75" stroke-linecap="round"/>
          </svg>
        </span>
      </h1>
      <p class="prose mx-auto text-xl py-4 leading-10	">
        Choosing simplicity is not giving up, it's prioritizing what is essential.
      <br>
        Dress in the basics. Live with intention.
      </p>

      <a href="#products" class="btn btn-primary mt-5">
        <i class="fas fa-arrow-down"></i>
        Conocenos
      </a>
    </div>
  </div>
</section>

<section id="products-list" class="flex flex-col items-center justify-center">
  <h2 class="font-bold text-[4rem] mx-auto">
    Our Products
  </h2>
  <%= form_tag landing_path, method: :get, class: "flex flex-col md:flex-row gap-3 items-center justify-center py-4" do %>
    <%= text_field_tag :query,
                       params[:query],
                       placeholder: "Search products...",
                       class: "input input-bordered w-full" %>


    <%= submit_tag "Search",
                   class: "btn btn-outline w-full lg:btn-wide" %>

    <%= link_to "Reset",
                landing_path,
                class: "btn btn-ghost join-item" %>
  <% end %>

  <div class="hero-content text-center">
    <div id="products" class="w-full flex flex-wrap gap-4 items-center justify-center">
      <%= render partial: "product_mini", collection: @products, as: :product %>
    </div>
  </div>
  <% if @products.blank? %>
    <p>We didn't find any products. We are sorry :(</p>
  <% else %>
    <%== pagy_nav(@pagy) %>
    <a href="#products-list" class="btn btn-wide btn-ghost">
      Go back
      <i class="fas fa-arrow-up"></i>
    </a>
  <% end %>


</section>

<%= render "shared/footer" %>

app/views/landing/show.html.erb
<% content_for :title do %>
  Avivas - Sport Clothing Store
<% end %>
<% content_for :header do %>
  <%= render "shared/navbar" %>
<% end %>
<section class="hero bg-base-100 min-h-screen max-w-screen-lg">
  <div class="hero-content flex-col lg:flex-row w-full -mt-[7.5rem]">
    <div class="carousel carousel-vertical rounded-box">
      <% if @product.images.present? %>
        <% @product.images.each do |image| %>
          <div class="carousel-item h-full">
            <%= image_tag image, class: "max-w-sm" %>
          </div>
        <% end %>
      <% else %>
        <%= image_tag product_image_url(@product), class: "max-w-sm" %>
    <% end %>
    </div>
    <div class="max-w-xl">
      <h1 class="text-5xl font-bold"><%= @product.name %></h1>
      <p class="py-6 prose">
        <%= @product.description %>
      </p>
      <div class="flex flex-col gap-2">
        <p><strong>Price: </strong><%= number_to_currency(@product.base_price) %></p>
        <p><strong>Color:  </strong><%= @product.color %></p>
        <p><strong>Units available: </strong><%= @product.stock_quantity %></p>
      </div>
    </div>
  </div>
</section>

<section>

</section>
<%= render "shared/footer" %>