config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "landing#index"
  post "/" => "landing#index", as: "landing"
  get "/show/:id" => "landing#show", as: :show_product

  namespace :admin do
    root to: "dashboard#index"
    get "profiles/edit"
    patch "profiles/update"
    get "profiles/:username", to: "profiles#show", as: "public_profile"
    get "users/search", to: "users#search"
    get "products/search", to: "products#search"
    resources :invoices, except: [ :edit, :update ] do
      member do
        patch :cancel
      end
    end
    resources :users do
      member do
        post :block
        post :activate
      end
    end
    namespace :products do
      resources :categories, except: :show
    end
    resources :products do
      member do
        get :update_stock
        patch :update_stock
        post :publish
        post :hide
        get :add_images
        delete :destroy_image
      end
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [ :create, :new ]
  resource :session, controller: "clearance/sessions", only: [ :create ]

  resources :users, controller: "clearance/users", only: [ :create ] do
    resource :password,
      controller: "clearance/passwords",
      only: [ :edit, :update ]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"

  # scope module: "storefront" do
  # end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  has_many :items, class_name: "Invoice::Item"
  has_many :products, through: :items

  accepts_nested_attributes_for :items, allow_destroy: true

  validates :user, presence: true
  validates :items, presence: true 
  validates :status, presence: true # Ensure status is always present

  enum :status, { active: 0, canceled: 1 }

  def cancel!
    return if canceled?

    ActiveRecord::Base.transaction do
      # Mark the invoice as canceled
      update!(status: :canceled)

      # Restore stock for each product in the invoice
      items.each do |item|
        product = item.product
        product.update!(stock_quantity: product.stock_quantity + item.units)
      end
    end
  end

  def calculate_total
    items.sum { |item| item.units * item.price }
  end
end

app/models/invoice/item.rb
class Invoice::Item < ApplicationRecord
  belongs_to :invoice
  belongs_to :product

  validates :product, presence: true
  validates :units, presence: true, numericality: { greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def total_price
    product.price * units
  end
end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < ApplicationController
  include Pundit::Authorization
  layout "admin"
  before_action :set_invoice, only: %i[ show cancel ]
  before_action :require_login

  # GET /admin/invoices or /admin/invoices.json
  def index
    authorize Invoice
    @invoices = Invoice.all
    if params[:order].present?
      @query = @query.order(params[:order])
    end

    @total_invoices_count = Invoice.count
    @filtered_invoices_count = @invoices.count

    @pagy, @invoices = pagy(@invoices)
  end

  # GET /admin/invoices/1 or /admin/invoices/1.json
  def show
    authorize @invoice
  end

  # GET /admin/invoices/new
  def new
    @invoice = Invoice.new
    authorize @invoice
    @invoice.items.build
  end

  def create
    authorize Invoice
    @invoice = Invoice.new(invoice_params)
    Rails.logger.debug("Invoice params: #{invoice_params.inspect}")
    success = false
  
    ActiveRecord::Base.transaction do
      if @invoice.save
        insufficient_stock = []
  
        @invoice.items.each do |item|
          product = item.product
          product.reload(lock: true) 
  
          if product.stock_quantity < item.units
            insufficient_stock << product.name
          end
        end
  
        if insufficient_stock.any?
          flash[:alert] = "Insufficient stock for: #{insufficient_stock.join(', ')}"
          raise ActiveRecord::Rollback
        end
  
        @invoice.items.each do |item|
          product = item.product
          product.update!(stock_quantity: product.stock_quantity - item.units)
        end
  
        success = true
        
      else
        flash[:alert] = "Unable to save invoice: #{@invoice.errors.full_messages.join(', ')}"
        raise ActiveRecord::Rollback
      end
    end
  
    if success
      redirect_to [:admin, @invoice], notice: "Invoice was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end


  # PATCH /admin/invoices/:id/cancel
  def cancel
    authorize @invoice
    Rails.logger.debug "Canceling invoice #{@invoice.id}..."
  
    if @invoice.cancel!
      redirect_to [:admin, @invoice], notice: "Invoice was successfully canceled."
    else
      Rails.logger.error "Failed to cancel invoice: #{@invoice.errors.full_messages.join(', ')}"
      redirect_to [:admin, @invoice], alert: "Unable to cancel the invoice: #{@invoice.errors.full_messages.join(', ')}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params.expect(:id))
    end
    def invoice_params
      params.require(:invoice).permit(
        :transaction_date,
        :notes,
        :total_price,
        :user_id,
        items_attributes: [:product_id, :units, :price, :_destroy]
      )
    end
end

app/helpers/admin/invoices_helper.rb
module Admin::InvoicesHelper
end

app/views/admin/invoices/_form.html.erb
<%= form_with(model: [:admin, invoice], class: "contents max-w-screen-lg") do |form| %>
  <div
    data-controller="search-user"
    class="form-control w-full"
  >
    <%= form.label :user_id, "Select user involved", class: "label" %>

    <div class="relative">
      <div class="w-full">
        <%= text_field_tag :query,
                           nil,
                           placeholder: "Search users...",
                           class: "input input-bordered w-full",
                           data: {
                             action: "input->search-user#search",
                             search_user_target: "searchInput"
                           }
        %>
      </div>
      <div
        id="user_results"
        data-search-user-target="results"
        class=" z-10 w-full mt-1 max-h-60 overflow-y-auto"
      >
      </div>
      <div id="selected_user_display" class="mt-2">
        <strong>Selected User:</strong>
        <span data-search-user-target="selectedUserDisplay"></span>
      </div>

      <%= form.hidden_field :user_id, id: "selected_user_id", data: { search_user_target: "selectedUserId" }%>
    </div>
  </div>
  <div class="form-control">
    <%= form.label :transaction_date, class: "label" %>
    <%= form.datetime_local_field :transaction_date, value: @invoice.transaction_date, class: "input input-bordered" %>
  </div>
  <div class="form-control col-span-2">
    <%= form.label :notes, class: "label" %>
    <%= form.text_area :notes, rows: 5, class: "input input-bordered" %>
  </div>
  <div
    data-controller="search-products"
    class="form-control w-full mb-4"
  >
    <%= label_tag :search_products, "Add Products", class: "label" %>

    <div class="relative">
      <%= text_field_tag :search_products,
                         nil,
                         placeholder: "Search products...",
                         class: "input input-bordered w-full",
                         data: {
                           action: "input->search-products#search",
                           search_products_target: "searchInput"
                         }
      %>

      <div
        id="product_results"
        data-search-products-target="results"
        class="z-10 w-full mt-1 max-h-60 overflow-y-auto"
      >
        <!-- Dynamic product search results -->
      </div>
    </div>

    <div
      id="selected-products"
      class="py-4"
    >
      <!-- Dynamically added selected products will appear here -->
    </div>


    <div class="flex justify-between mt-4">
      <span class="font-bold">Total:</span>
      <span class="font-bold text-lg">
        <%= form.number_field :total_price,
                              class: "input input-bordered w-full",
                              id: 'invoice-total-price',
                              value: 0,
                              step: "0.01",
                              min: "0",
                              precision: 2
        %>
      </span>
    </div>
  </div>

  <div class="flex justify-end mt-4">
    <%= form.submit "Save Invoice", class: "btn btn-outline btn-wide rounded-lg w-full" %>
  </div>
<% end %>

app/views/admin/invoices/_invoice.html.erb
<h2 class="card-title">Invoice #<%= @invoice.id %></h2>
<div class="stats shadow">
  <div class="stat">
    <div class="stat-figure text-secondary">
      <div class="avatar online">
        <div class="w-16 rounded-full">
          <%= image_tag avatar_url(@invoice.user), alt: "#{invoice.user.username}'s avatar", class: "user-avatar" %>
        </div>
      </div>
    </div>
    <div class="stat-title"><%= @invoice.user.full_name %></div>
    <div class="stat-value"><%= @invoice.user.username %></div>
  </div>
</div>

<div class="flex justify-between">
  <div>
    <p><strong>Transaction Date:</strong> <%= @invoice.transaction_date.strftime("%B %d, %Y") %></p>
    <p><strong>Notes:</strong> <%= @invoice.notes %></p>
    <p><strong>Total Price:</strong> <%= number_to_currency(@invoice.total_price) %></p>
  </div>

</div>

app/views/admin/invoices/_invoice_row.html.erb
<tr>
  <td>
    <div class="flex items-center gap-3">
      <div class="avatar">
        <div class="mask mask-squircle h-12 w-12">
          <%= image_tag avatar_url(invoice.user), alt: "#{invoice.user.username}'s avatar", class: "user-avatar" %>
        </div>
      </div>
      <div>
        <div class="font-bold"><%= invoice.user.full_name %></div>
        <div class="text-sm opacity-50"><%= invoice.user.role.capitalize %></div>
      </div>
    </div>
  </td>

  <td>
    <%= invoice.total_price %>
  </td>
  <td>
    <%= time_ago_in_words(invoice.transaction_date) %>
  </td>
  <td>
    <%= link_to "details", admin_invoice_path(invoice), class: "btn btn-ghost btn-md text-xs" %>
  </td>
</tr>

app/views/admin/invoices/_invoices_table.html.erb
<table class="table">
  <!-- head -->
  <thead>
  <tr>
    <th>Made by</th>
    <th>Total Amount</th>
    <th>Made at</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @invoices.each do |invoice| %>

    <%= render partial: "invoice_row", locals: { invoice: invoice } %>

  <% end %>
  </tbody>
  <!-- foot -->
  <tfoot>
  <tr>
    <th>Made by</th>
    <th>Total Amount</th>
    <th>Made at</th>
    <th></th>
  </tr>
  </tfoot>
</table>

app/views/admin/invoices/index.html.erb
<section class="w-full mx-auto">
  <% content_for :title, "Invoices" %>

  <header class="flex justify-between">
    <h1 class="font-bold text-4xl">
      <i class="fas fa-file-invoice px-2"></i>
      Invoices
    </h1>
    <%= link_to new_admin_invoice_path, class: "btn btn-outline rounded-lg py-3 px-5" do %>
      <i class="fas fa-plus"></i> Record a sale
    <% end %>
  </header>

  <article id="users-stats" class="flex justify-between items-center max-w-screen-2xl py-4 ">
    <div class="stats stats-vertical sm:stats-horizontal mx-auto shadow w-full">
      <div class="stat place-items-center">
        <div class="stat-title">Downloads</div>
        <div class="stat-value">31K</div>
        <div class="stat-desc">Jan 1st - Feb 1st</div>
      </div>

      <div class="stat place-items-center">
        <div class="stat-title">New Users</div>
        <div class="stat-value">4,200</div>
        <div class="stat-desc">↗︎ 400 (22%)</div>
      </div>

      <div class="stat place-items-center">
        <div class="stat-title">New Registers</div>
        <div class="stat-value">1,200</div>
        <div class="stat-desc">↘︎ 90 (14%)</div>
      </div>
    </div>
  </article>

  <article id="invoices" class="max-w-screen-xl mx-auto mt-4">
    <%= form_tag admin_invoices_path, method: :get, class: "flex flex-col md:flex-row gap-3 items-center justify-center py-2" do %>
      <%= text_field_tag :query,
                         params[:query],
                         placeholder: "Search invoices...",
                         class: "input input-bordered w-full" %>

      <%= submit_tag "Search",
                     class: "btn btn-outline w-full md:btn-wide" %>

      <%= link_to "Reset",
                  admin_invoices_path,
                  class: "btn btn-ghost join-item" %>
    <% end %>

    <div class="overflow-x-auto flex flex-col justify-center items-center pt-4">

      <%== pagy_nav(@pagy) %>
      <%= render "invoices_table", locals: { invoices: @invoices } %>
      <%== pagy_nav(@pagy) %>

    </div>
  </article>
</section>

app/views/admin/invoices/new.html.erb
<% content_for :title, "Recording Invoice" %>

<section class="w-full">
  <header class="flex justify-between">
    <h1 class="font-bold text-4xl">
      <i class="fa-solid fa-plus pr-2"></i>
      New Invoice
    </h1>
    <%= link_to admin_invoices_path, class: "btn btn-ghost" do %>
      <i class="fas fa-arrow-left"></i> Back to invoices
    <% end %>
  </header>

  <article class="mx-auto px-4 max-w-screen-lg">
    <%= render "form", invoice: @invoice %>
  </article>

</section>

app/views/admin/invoices/show.html.erb
<% content_for :title, "Showing Invoice" %>

<section class="flex flex-col gap-4 mx-auto">
  <header class="flex justify-between">
    <h1 class="font-bold text-xl md:text-4xl">
      <i class="fas fa-eye pr-2"></i>
      Showing Invoice #<%= @invoice.id %></h1>
    <%= link_to admin_invoices_path, class: "btn btn-sm btn-ghost" do %>
      <i class="fas fa-arrow-left"></i> Back to invoices
    <% end %>
  </header>

  <article id="actions">
    <details class="collapse bg-base-100 collapse-arrow border-2 border-base-300 rounded-lg shadow-md">
      <summary class="collapse-title font-medium">
        <i class="fa-solid fa-wand-magic-sparkles mr-1 text-xl"></i>
        Actions
      </summary>
      <div class="collapse-content">
        <div class="flex flex-wrap gap-2 justify-evenly">
          <% unless @invoice.canceled? %>
            <%= form_with url: cancel_admin_invoice_path(@invoice), method: :patch, class: "inline" do %>
              <%= button_tag "Cancel Invoice",
                            type: "submit",
                            data: { confirm: "Are you sure you want to cancel this invoice?" },
                            class: "btn btn-danger" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </details>
  </article>

  <section id="user-information" class="flex justify-center mt-4">
    <div class="card indicator md:card-side bg-base-100 shadow-xl">
      <span class="indicator-item indicator-top indicator-center badge badge-lg badge-primary p-6 text-xl font-bold rounded-lg">
        <%= @invoice.status.capitalize %>
      </span>
      <div class="card-body">
        <%= render @invoice %>
      </div>
    </div>

  </section>

  <section class="card w-full max-w-2xl shadow-lg bg-base-100">
    <div class="card-body">
      <h3 class="card-title">Products</h3>
      <table class="table table-zebra w-full">
        <thead>
          <tr>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
        <% @invoice.items.each do |item| %>
          <tr>
            <td><%= item.product.name %></td>
            <td><%= item.units %></td>
            <td><%= number_to_currency(item.price) %></td>
            <td><%= number_to_currency(item.units * item.price) %></td>
            <td>
              <%= link_to "details", admin_product_path(item.product), class: "btn btn-ghost btn-md text-xs" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </section>
</section>