config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "landing#index"
  post "/" => "landing#index", as: "landing"
  get "/show/:id" => "landing#show", as: :show_product

  namespace :admin do
    root to: "dashboard#index"
    get "profiles/edit"
    patch "profiles/update"
    get "profiles/:username", to: "profiles#show", as: "public_profile"
    get "users/search", to: "users#search"
    get "products/search", to: "products#search"
    resources :invoices, except: [ :edit, :update ] do
      member do
        patch :cancel
      end
    end
    resources :users do
      member do
        post :block
        post :activate
      end
    end
    namespace :products do
      resources :categories, except: :show
    end
    resources :products do
      member do
        get :update_stock
        patch :update_stock
        post :publish
        post :hide
        get :add_images
        delete :destroy_image
      end
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [ :create, :new ]
  resource :session, controller: "clearance/sessions", only: [ :create ]

  resources :users, controller: "clearance/users", only: [ :create ] do
    resource :password,
      controller: "clearance/passwords",
      only: [ :edit, :update ]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"

  # scope module: "storefront" do
  # end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
  has_and_belongs_to_many :collections
  has_and_belongs_to_many :categories,
                          join_table: "product_categories_products",
                          foreign_key: :product_id,
                          association_foreign_key: :product_category_id
  has_many :items
  has_many :invoices, through: :items

  validates :name, presence: true, length: { maximum: 255 }
  validates :color, length: { maximum: 50 }
  validates :sizes_available, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 10000 }
  validates :base_price, numericality: { greater_than_or_equal_to: 0 }
  validates :stock_quantity, numericality: { greater_than_or_equal_to: 0 }

  scope :by_name_or_description, ->(query) { where("lower(name) LIKE :search OR lower(description) LIKE :search",
                                             search: "%#{query.downcase}%")
  }
  scope :deleted_ones, ->(flag) { where(deleted: flag) }
  scope :deleted_count, -> { where(deleted_at: nil).count }
  scope :published_count, -> { where(published: true).count }
  scope :published_products, -> { where(published: true) }
  scope :by_category, ->(category) { where(category: category) }

  def published?
    self.published
  end

  def total_units_sold
    items.sum(:units)
  end

  def delete
    self.deleted = true
    self.deleted_at = Time.zone.now
    self.published = false
    self.stock_quantity = 0
    self.save
  end

  def product_image_url
    if images.attached?
      Rails.application.routes.url_helpers.rails_blob_path(images.first, only_path: true)
    else
      "/images/default_product.webp"
    end
  end
end

app/models/product/category.rb
class Product::Category < ApplicationRecord
  has_one_attached :icon
  has_and_belongs_to_many :products,
                          join_table: "product_categories_products",
                          foreign_key: :product_category_id,
                          association_foreign_key: :product_id

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 10000 }
end

app/models/product/collection.rb
class Product::Collection < ApplicationRecord
  has_many_attached :images
  has_and_belongs_to_many :product

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 10000 }
end

app/models/products/category.rb
class Products::Category < ApplicationRecord
  has_one_attached :icon
  has_and_belongs_to_many :products

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 10000 }
end

app/models/products/collection.rb
class Products::Collection < ApplicationRecord
  has_many_attached :images
  has_and_belongs_to_many :products

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 10000 }
end

app/controllers/admin/products/categories_controller.rb
class Admin::Products::CategoriesController < ApplicationController
  layout "admin"
  before_action :set_product_category, only: %i[ edit update destroy ]
  before_action :require_login

  # GET /admin/products/categories or /admin/products/categories.json
  def index
    @product_category = Product::Category.new
    @product_categories = Product::Category.all
  end

  # GET /admin/products/categories/new
  def new
    @product_category = Product::Category.new
  end

  # GET /admin/products/categories/1/edit
  def edit
  end

  # POST /admin/products/categories or /admin/products/categories.json
  def create
    @product_category = Product::Category.new(product_category_params)

    respond_to do |format|
      if @product_category.save
        format.html { redirect_to admin_products_categories_path, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @product_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/categories/1 or /admin/products/categories/1.json
  def update
    respond_to do |format|
      if @product_category.update(product_category_params)
        format.html { redirect_to admin_products_categories_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @product_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/categories/1 or /admin/products/categories/1.json
  def destroy
    @product_category.products.clear

    category = @product_category.name
    puts category
    @product_category.destroy!

    respond_to do |format|
      format.html { redirect_to admin_products_category_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_category
      @product_category = Product::Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def product_category_params
      params.require(:product_category).permit(:name, :description, :active)
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  include Pundit::Authorization
  layout "admin"
  before_action :set_admin_product, only: %i[ show edit update destroy update_stock publish hide add_images destroy_image ]
  before_action :require_login

  # GET /admin/products or /admin/products.json
  def index
    @products = Product.all
    authorize Product
    params[:deleted] = false unless params[:deleted].present?
    @products= @products.by_name_or_description(params[:query]) if params[:query].present?
    @products = @products.deleted_ones(params[:deleted])

    @total_products_count = Product.all.count
    @total_products_published = Product.published_count
    @total_products_deleted = Product.deleted_count
    @pagy, @products = pagy(@products)
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
    authorize @product
  end

  # GET /admin/products/new
  def new
    @product = Product.new
    authorize @product
  end

  # GET /admin/products/1/edit
  def edit
    authorize @product
  end

  # POST /admin/products or /admin/products.json
  def create
    authorize Product
    category_ids = params.dig(:product, :categories)&.reject(&:blank?)
    product_params = admin_product_params.except(:categories)
    @product = Product.new(product_params)
    @product.category_ids = category_ids if category_ids.present?
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    authorize @product
    category_ids = params.dig(:product, :categories)&.reject(&:blank?)
    product_params = admin_product_params.except(:categories)

    respond_to do |format|
      if @product.update(product_params)
        @product.category_ids = category_ids if category_ids.present?

        format.html { redirect_to admin_product_path @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    authorize @product
    @product.delete

    respond_to do |format|
      format.html { redirect_to admin_products_path, status: :see_other, notice: "Product was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def update_stock
    authorize @product
    if @product.update(stock_quantity: params[:stock_quantity])
      render :show
    else
      @product.errors.clear unless request.patch?
      render partial: "admin/products/shared/update_stock", locals: { product: @product }
    end
  end

  def add_images
    authorize @product
    if params[:images].present?
      params[:images].each do |image|
        @product.attachment.attach(image)
      end
      flash[:notice] = "Images uploaded successfully"
      redirect_to admin_product_path(@product)
    else
      @product.errors.clear unless request.patch?
      render partial: "admin/products/shared/image_form", locals: { product: @product }
    end
  end

  def destroy_image
    authorize @product
    image = @product.images.find(params[:image_id])
    if image.purge
      flash[:notice] = "Image deleted successfully"
      redirect_to admin_product_path(@product)
    else
      flash[:notice] = "Image could not be deleted"
      redirect_to admin_product_path(@product)
    end
  end

  def publish
    authorize @product
    if @product.update(published: true)
      flash[:notice] = "Product published successfully"
      redirect_to admin_product_path @product
    else
      render :show
    end
  end

  def hide
    authorize @product
    if @product.update(published: false)
      flash[:notice] = "Product hidden successfully"
      redirect_to admin_product_path @product
    else
      render :show
    end
  end

  def search
    authorize Product
    @products = Product.by_name_or_description(params[:query])
    @products = @products.where(deleted: false).limit(5)

    render(
      partial: "admin/products/shared/search_results",
      formats: [ :turbo_stream ]
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @product = Product.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.require(:product).permit(
        :name,
        :description,
        :base_price,
        :stock_quantity,
        :image,
        :color,
        :sizes_available,
        images: [],
        categories: [],
      )
    end
end

app/helpers/admin/products/categories_helper.rb
module Admin::Products::CategoriesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def humanize_boolean(value)
    value ? "Yes" : "No"
  end

  def humanize_published(value)
    value ? "Published" : "Hidden"
  end

  def product_image_url(product)
    if product.images.attached?
      Rails.application.routes.url_helpers.rails_blob_path(product.images.first, only_path: true)
    else
      "/images/default_product.webp"
    end
  end
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product], class: "form-control gap-2 w-full") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="flex flex-col items-center alert alert-error px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-control w-full">
    <%= form.label :name, class: "label" %>

    <%= form.text_field :name, class: "input input-bordered w-full" %>
  </div>

  <div class="form-control w-full">
    <%= form.label :description, class: "label" %>

    <%= form.text_area :description, rows: 4, class: "textarea textarea-bordered w-full" %>
  </div>

  <div class="form-control w-full">
    <%= form.label :color, class: "label" %>

    <%= form.text_field :color, class: "input input-bordered w-full", placeholder: "White" %>
  </div>

  <div class="form-control w-full">
    <%= form.label :sizes_available, class: "label" %>

    <%= form.text_field :sizes_available, class: "input input-bordered w-full", placeholder: "XS S M L"%>
  </div>

  <div class="form-control w-full">
    <%= form.label :base_price, class: "label" %>

    <%= form.number_field :base_price, step: 0.5, class: "input input-bordered w-full" %>
  </div>
  <div class="form-control">
    <label for="categories" class="label">Categories</label>
    <%= form.collection_select :categories, Product::Category.all, :id, :name,  class:"select select-bordered w-full max-w-xs text-black", multiple: true %>
  </div>
  <div class="form-control w-full">
    <%= form.label :stock_quantity, class: "label" %>

    <%= form.number_field :stock_quantity, class: "input input-bordered w-full" %>
  </div>
  <div class="form-control w-full">
    <%= form.label :images, class: "label" %>
    <%= form.file_field :images, multiple: true, accept: 'image/png,image/jpeg,image/jpg', class: "file-input file-input-bordered w-full" %>
  </div>

  <div class="form-control mt-4">
    <%= form.submit class: "btn btn-outline" %>
  </div>

<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>" class="card lg:card-side bg-base-100 shadow">
  <div class="card-body">
    <h2 class="card-title"><%= product.name %></h2>
    <p><%= product.description %></p>
    <p>Price: <%= number_to_currency(product.base_price) %></p>
    <p>Stock: <%= product.stock_quantity %></p>
    <p>Published: <%= product.published ? 'Yes' : 'No' %></p>
    <% if product.deleted %>
      <p>Deleted At: <span class="badge badge-lg badge-error"><%= product.deleted_at %></p>
    <% end %>
    <p>Created at: <%= time_ago_in_words(product.created_at) %> ago</p>
    <p>Updated at: <%= time_ago_in_words(product.updated_at) %> ago</p>

  </div>

  <figure class="card-figure max-w-md">
    <%= image_tag product.product_image_url, class: "" %>
  </figure>
</div>

app/views/admin/products/_product_row.html.erb
<tr>
  <td>
    <div class="flex items-center gap-3">
      <div class="avatar">
        <div class="mask mask-squircle h-12 w-12">
          <%= image_tag product_image_url(product) %>
          <div class="bg-gray-100 mask mask-squircle h-12 w-12"></div>
        </div>
      </div>
    </div>
  </td>
  <td>
    <div>
      <div class="font-bold"><%= product.name %></div>
      <div class="text-sm opacity-50"></div>
    </div>
  </td>
  <td>
    <%= product.base_price %>
  </td>
  <td>
    <%= product.stock_quantity %>
  </td>
  <td>
    <span class="badge badge-secondary p-4 rounded-lg badge-sm">
      <%= humanize_published product.published %>
    </span>
  </td>
  <th>
    <%= link_to "details", [:admin, product], class: "btn btn-ghost btn-md text-xs" %>
  </th>
</tr>

app/views/admin/products/_products_table.html.erb
<table class="table">
  <!-- head -->
  <thead>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Price</th>
    <th>Stock</th>
    <th>Published</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>

    <%= render partial: "admin/products/product_row", locals: { product: product } %>

  <% end %>
  </tbody>
  <!-- foot -->
  <tfoot>
  <tr>
    <th></th>
    <th>Price</th>
    <th>Name</th>
    <th>Stock</th>
    <th>Published</th>
    <th></th>
  </tr>
  </tfoot>
</table>

app/views/admin/products/edit.html.erb
<% content_for :title, "Updating Product" %>

<section class="w-full">
  <header class="flex justify-between">
    <h1 class="font-bold text-4xl">
      <i class="fa-solid fa-user-pen pr-2"></i>
      Updating product
    </h1>
    <%= link_to admin_product_path @product, class: "btn btn-ghost" do %>
      <i class="fas fa-arrow-left"></i> Back to products
    <% end %>
  </header>

  <%= link_to [:admin, @product], class: "btn btn-ghost mx-auto pl-0 hover:bg-transparent" do %>
    Show this product
    <i class="fas fa-eye text-xl"></i>
  <% end %>
  <article class="max-w-lg mx-auto">
    <%= render "form", product: @product %>
  </article>

</section>

app/views/admin/products/index.html.erb
<section class="w-full mx-auto">
  <% content_for :title, "Users" %>

  <header class="flex justify-between">
    <h1 class="font-bold text-4xl">
      <i class="fas fa-users px-2"></i>
      Products
    </h1>
    <%= link_to new_admin_product_path, class: "btn btn-outline rounded-lg py-3 px-5" do %>
      <i class="fas fa-plus"></i> Add Product
    <% end %>
  </header>

  <article id="users-stats" class="flex justify-between items-center max-w-screen-2xl py-4 ">
    <div class="stat place-items-center">
      <div class="stat-title">Total Products</div>
      <%= render 'shared/animated_number',
                 message: @total_products_count,
                 start_value: 0,
                 end_value: @total_products_count,
                 classes: "stat-value" %>
      <div class="stat-desc"></div>
    </div>

    <div class="stat place-items-center">
      <div class="stat-title">Published Products</div>
      <%= render 'shared/animated_number',
                 message: @total_products_published,
                 start_value: 0,
                 end_value: @total_products_published,
                 classes: "stat-value" %>
      <div class="stat-value"></div>
      <div class="stat-desc"></div>
    </div>

    <div class="stat place-items-center">
      <div class="stat-title">Deleted Products</div>
      <%= render 'shared/animated_number',
                 message: @total_products_deleted,
                 start_value: 0,
                 end_value: @total_products_deleted,
                 classes: "stat-value" %>
      <div class="stat-desc"></div>
    </div>
  </article>

  <article id="users" class="max-w-screen-xl mx-auto mt-4">
    <%= form_tag admin_products_path, method: :get, class: "flex flex-col md:flex-row gap-3 items-center justify-center py-2" do %>
      <%= text_field_tag :query,
                         params[:query],
                         placeholder: "Search products...",
                         class: "input input-bordered w-full" %>
      <%= select_tag :deleted, options_for_select([["Active", false], ["Deleted", true]]),
                     class: 'select select-bordered  max-w-xs' %>


      <%= submit_tag "Search",
                     class: "btn btn-outline w-full md:btn-wide" %>

      <%= link_to "Reset",
                  admin_users_path,
                  class: "btn btn-ghost join-item" %>
    <% end %>

    <div class="overflow-x-auto flex flex-col justify-center items-center pt-4">

      <%== pagy_nav(@pagy) %>
      <%= render "products_table", locals: { products: @products } %>
      <%== pagy_nav(@pagy) %>

    </div>
  </article>
</section>

app/views/admin/products/new.html.erb
<% content_for :title, "Adding Product" %>

<section class="w-full">
  <header class="flex justify-between">
    <h1 class="font-bold text-4xl">
      <i class="fa-solid fa-user-plus pr-2"></i>
      New Product
    </h1>
    <%= link_to admin_products_path, class: "btn btn-ghost" do %>
      <i class="fas fa-arrow-left"></i> Back to products
    <% end %>
  </header>

  <article class="max-w-lg mx-auto">
    <%= render "form", product: @product %>
  </article>

</section>

app/views/admin/products/show.html.erb
<% content_for :title, "Showing Product" %>

<section class="flex flex-col gap-4 mx-auto">
  <header class="flex justify-between">
    <h1 class="font-bold text-xl md:text-4xl">
      <i class="fas fa-eye pr-2"></i>
      <%= @product.name %></h1>
    <%= link_to admin_products_path, class: "btn btn-ghost" do %>
      <i class="fas fa-arrow-left"></i> Back to products
    <% end %>
  </header>

  <article id="actions" class="">
    <details class="collapse bg-base-100 collapse-arrow border-2 border-base-300 rounded-lg shadow-md">
      <summary class="collapse-title font-medium">
        <i class="fa-solid fa-wand-magic-sparkles mr-1 text-xl"></i>
        Actions
      </summary>
      <div class="collapse-content">
        <div class="flex flex-wrap gap-2 justify-evenly">
          <%= button_to [:admin, @product], method: :delete, class: "btn btn-outline btn-lg lg:btn-wide" do %>
            <i class="fas fa-trash-alt"></i> Destroy
          <% end %>
          <% if @product.published? %>
            <%= button_to hide_admin_product_path(@product), method: :post, class: "btn btn-outline btn-lg lg:btn-wide" do %>
              <i class="fas fa-cloud-upload-alt"></i>
              Hide
            <% end %>
          <% else %>
            <%= button_to publish_admin_product_path(@product), method: :post, class: "btn btn-outline btn-lg lg:btn-wide" do %>
              <i class="fas fa-paper-plane"></i>
              Publish
            <% end %>
          <% end %>
          <%= link_to edit_admin_product_path(@product), class: "btn btn-outline btn-lg lg:btn-wide" do %>
            <i class="fas fa-edit"></i> Update
          <% end %>
        </div>
      </div>
    </details>
  </article>

  <section id="product-information" class="w-full mt-4 indicator">
    <p class="indicator-item indicator-center mx-auto font-bold text-xl badge badge-xl badge-primary p-4 rounded-lg">
      Status: <%= humanize_published @product.published? %>
    </p>
    <div class="card md:card-side bg-base-100 shadow-xl mx-auto">
      <%= image_tag @product.product_image_url, size: 300, class: "max-w-md object-cover" %>
      <%#= render partial: "shared/carousel", locals: { images: @product.images, default_image: @product.product_image_url  } %>
      <div class="card-body grow ">
        <div class="flex flex-col gap-3">
          <h2 class="card-title"><%= @product.name %></h2>
          <p><%= @product.description %></p>
          <p>
            <i class="fas fa-dollar-sign"></i>
            <strong>Price: </strong><%= number_to_currency(@product.base_price) %>
          </p>
          <%= turbo_frame_tag dom_id(@product) do %>
            <label>
              <i class="fas fa-boxes"></i>
              <span class="pr-2"><strong>Stock: </strong> <%= @product.stock_quantity %></span>
              <%= link_to update_stock_admin_product_path(@product), class: "btn btn-outline rounded-lg" do %>
                Modify <i class="fas fa-pencil"></i>
              <% end %>
            </label>
          <% end %>
          <p>
            <strong>Color: </strong><%= @product.color.blank? ? "Not specified" : @product.color %>
          </p>
          <p>
            <strong>Sizes available: </strong><%= @product.sizes_available.blank? ? "Not specified" : @product.sizes_available %>
          </p>
          <ul class="flex flex-wrap gap-2">
            <strong>Categories: </strong>
            <% if @product.categories.count > 0 %>
              <% @product.categories.each do |category| %>
                <li><%= category.name %>, </li>
              <% end %>
            <% else %>
              <p> Unassigned</p>
            <% end %>
          </ul>
          <% if @product.deleted %>
            <p>Deleted At: <span class="badge badge-lg badge-error"><%= @product.deleted_at %></p>
          <% end %>
        </div>
        <div class="card-actions justify-end">
          <p>
            <i class="fas fa-history"></i>
            Created <%=  time_ago_in_words(@product.created_at) %> ago
          </p>
          <p>
            <i class="fas fa-sync"></i>
            Last update <%= time_ago_in_words(@product.updated_at) %> ago</p>
        </div>
      </div>
    </div>
  </section>

  <section id="product-images">
    <div tabindex="0" class="collapse collapse-open collapse-plus border-base-300 bg-base-100 border border-1 rounded-lg shadow-md">
      <div class="collapse-title text-xl font-medium">
        <i class="fas fa-photo-film"></i>
        Images
        <%= @product.images.count %>
      </div>
      <div class="collapse-content flex flex-col items-center">
        <%= turbo_frame_tag dom_id(@product, :images), class: "w-full max-w-screen-md" do %>
          <%= link_to add_images_admin_product_path(@product), class: "btn btn-outline btn-sm rounded-lg w-full px-4" do %>
            Add image
            <i class="fas fa-image"></i>
          <% end %>
        <% end %>
        <div class="flex flex-wrap gap-4 justify-center mt-5">
          <% if @product.images.attached? %>
            <% @product.images.each do |image| %>
              <div class="card relative">
                <img
                  src="<%= url_for(image) %>"
                  alt="Shoes"
                  width="300px"
                  height="300px"
                  class="object-cover"
                />
                <%= button_to "Delete", destroy_image_admin_product_path(@product, image_id: image.id), method: :delete, class:"btn btn-secondary absolute top-0" %>
              </div>
            <% end %>
          <% else %>
            <p>No images available</p>
          <% end %>
        </div>
      </div>
    </div>
  </section>

<!--  <section id="product-variants">-->
<!--    <div tabindex="0" class="collapse collapse-open border-base-300 bg-base-100 border border-1 rounded-lg shadow-md">-->
<!--      <div class="collapse-title text-xl font-medium">-->
<!--        <i class="fas fa-tags"></i>-->
<!--        Variants-->
<!--      </div>-->
<!--      <div class="collapse-content">-->
<!--      </div>-->
<!--    </div>-->
<!--  </section>-->
</section>