config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "landing#index"
  post "/" => "landing#index", as: "landing"
  get "/show/:id" => "landing#show", as: :show_product

  namespace :admin do
    root to: "dashboard#index"
    get "profiles/edit"
    patch "profiles/update"
    get "profiles/:username", to: "profiles#show", as: "public_profile"
    get "users/search", to: "users#search"
    get "products/search", to: "products#search"
    resources :invoices, except: [ :edit, :update ] do
      member do
        patch :cancel
      end
    end
    resources :users do
      member do
        post :block
        post :activate
      end
    end
    namespace :products do
      resources :categories, except: :show
    end
    resources :products do
      member do
        get :update_stock
        patch :update_stock
        post :publish
        post :hide
        get :add_images
        delete :destroy_image
      end
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [ :create, :new ]
  resource :session, controller: "clearance/sessions", only: [ :create ]

  resources :users, controller: "clearance/users", only: [ :create ] do
    resource :password,
      controller: "clearance/passwords",
      only: [ :edit, :update ]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"

  # scope module: "storefront" do
  # end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_one_attached :avatar
  has_many :invoices
  before_save :normalize_phone_number


  enum :role, [ :member, :employee, :manager, :admin ], suffix: true

  enum :status, [ :active, :inactive, :blocked ], suffix: true

  scope :by_name_or_email, ->(query) {
    where("LOWER(first_name) LIKE :search OR LOWER(username) LIKE :search OR LOWER(last_name) LIKE :search OR LOWER(email) LIKE :search",
          search: "%#{query.downcase}%")
  }

  scope :by_role, ->(role) {
    where(role: role)
  }
  scope :by_status, ->(status) {
    where(status: status)
  }

  validates :first_name,
            length: {
              minimum: 2,
              maximum: 50,
              allow_blank: true
            }

  validates :last_name,
            length: {
              minimum: 2,
              maximum: 50,
              allow_blank: true
            }

  validates :bio,
            length: { maximum: 250, allow_blank: true }

  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: {
              minimum: 3,
              maximum: 50
            },
            format: {
              with: /\A[a-zA-Z0-9_]+\z/,
              message: "can only contain letters, numbers, and underscores"
            }

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: {
              with: URI::MailTo::EMAIL_REGEXP,
              message: "must be a valid email address"
            }

  validates :phone,
            phone:
              {
                possible: true,
                allow_blank: true,
                types: [ :mobile ],
                countries: [ :ar, :us ]
              }

  validates :role,
            presence: true,
            inclusion: { in: roles.keys }

  validates :joined_at,
            presence: true,
            comparison: { less_than_or_equal_to: Date.today }

  def full_name
    "#{first_name} #{last_name}"
  end
  def admin?; admin_role?; end
  def manager?; manager_role?; end
  def employee?; employee_role?; end
  def blocked?; blocked_status?; end
  def active?; active_status?; end
  def inactive?; inactive_status?; end


  private
  def normalize_phone_number
    self.phone= Phonelib.parse(phone).international if phone.present?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  include Pundit::Authorization
  require "faker"
  layout "admin"
  before_action :set_user, only: %i[ show edit update ]
  before_action :require_login
  # before_action :skip_auth

  # GET /admin/users or /admin/users.json
  def index
    @users = User.all
    authorize User
    @users = @users.by_name_or_email(params[:query]) if params[:query].present?
    @users = @users.by_role(params[:role]) if params[:role].present?
    @users = @users.by_status(params[:status]) if params[:status].present?

    @total_users_last_month = User.where("created_at >= ?", 1.month.ago).count
    @total_users_count = User.count
    @total_users_active = User.where(status: :active).count
    @filtered_users_count = @users.count

    @pagy, @users = pagy(@users)
  end

  # GET /admin/users/1 or /admin/users/1.json
  def show
    authorize @user
  end

  # GET /admin/users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /admin/users/1/edit
  def edit
    authorize @user
  end

  # POST /admin/users or /admin/users.json
  def create
    @user = User.new(user_params)
    authorize @user
    password = Faker::Internet.password(min_length: 8, max_length: 8, special_characters: false)
    username = Faker::Internet.unique.user_name(separators: [ "" ])
    @user.password = BCrypt::Password.create(password)
    @user.username = user_params[:username] ? user_params[:username] : username
    respond_to do |format|
      if @user.save
        Admin::UserMailer.with(user: @user, password: password, username: username).account_creation_email.deliver_later
        format.html { redirect_to [ :admin, @user ], notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1 or /admin/users/1.json
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [ :admin, @user ], notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def block
    user = User.find(params[:id])
    authorize user
    user.status = :blocked
    if user.save!
      redirect_to [ :admin, user ], notice: "User was successfully blocked."
    else
      redirect_to [ :admin, user ], alert: "User was not blocked."
    end
  end

  def activate
    user = User.find(params[:id])
    authorize user
    new_password = SecureRandom.hex(8)
    user.status = :active
    user.password = BCrypt::Password.create(new_password)
    if user.save!
      Admin::UserMailer.with(user: user, password: new_password).account_recovery_email.deliver_later
      redirect_to [ :admin, user ], notice: "User was successfully unblocked."
    else
      redirect_to [ :admin, user ], alert: "User was not unblocked."
    end
  end

  def search
    authorize User
    @users = User.by_name_or_email(params[:query])
    @users = @users.where(status: :active).limit(5)
    render(
      partial: "admin/users/shared/search_results",
      formats: [ :turbo_stream ]
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end


    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :bio,
        :phone,
        :username,
        :email,
        :password,
        :role,
        :joined_at,
        :other_permitted_params)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def avatar_url(user)
    if user.avatar.attached?
      Rails.application.routes.url_helpers.rails_blob_path(user.avatar, only_path: true)
    else
      "/images/default_avatar.webp"
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user], local: true, class: "max-w-md") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <div>
        <span><%= pluralize(user.errors.count, "error") %> prohibited this admin_user from being saved:</span>
        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-control w-full">
    <%= form.label :first_name, class: "label" %>
    <%= form.text_field :first_name, class: "input input-bordered w-full" %>
  </div>

  <div class="form-control w-full">
    <%= form.label :last_name, class: "label" %>
    <%= form.text_field :last_name, class: "input input-bordered w-full" %>
  </div>

  <div class="form-control w-full">
    <%= form.label :username, class: "label" %>
    <%= form.text_field :username, class: "input input-bordered w-full" %>
  </div>

  <div class="form-control w-full">
    <%= form.label :email, class: "label" %>
    <%= form.text_field :email, class: "input input-bordered w-full" %>
  </div>

  <div class="form-control w-full">
    <%= form.label :phone, class: "label" %>
    <%= form.telephone_field :phone, class: "input input-bordered w-full" %>
  </div>

  <div class="form-control">
    <%= form.label :role, class: "label" %>
    <%= form.select :role, options_for_select(User.roles.keys.map { |role| [role.titleize, role] }, @user.role), {}, { class: "select select-bordered w-full" } %>
  </div>

  <div class="form-control w-full">
    <%= form.label :joined_at, class: "label" %>
    <%= form.date_field :joined_at, class: "input input-bordered w-full" %>
  </div>

  <div class="form-control mt-5">
    <%= form.submit "Submit", class: "btn btn-outline" %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="p-2">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= user.full_name %>
  </p>

  <p class="p-2">
    <strong class="block font-medium mb-1">Username:</strong>
    <%= user.username %>
  </p>

  <p class="p-2">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= user.email %>
  </p>

  <p class="p-2">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= user.phone %>
  </p>

  <p class="p-2">
    <strong class="block font-medium mb-1">Role:</strong>
    <%= user.role %>
  </p>

  <p class="p-2">
    <strong class="block font-medium mb-1">Joined at:</strong>
    <%= user.joined_at %>
  </p>

  <p class="p-2">
    <strong class="block font-medium mb-1">Created at:</strong>
    <%= time_ago_in_words(user.created_at) %> ago
  </p>

  <p class="p-2">
    <strong class="block font-medium mb-1">Joined at:</strong>
    <%= time_ago_in_words(user.updated_at)%> ago
  </p>
</div>

app/views/admin/users/_user_row.html.erb
<tr>
  <td>
    <div class="flex items-center gap-3">
      <div class="avatar">
        <div class="mask mask-squircle h-12 w-12">
          <%= image_tag avatar_url(user), alt: "#{user.username}'s avatar", class: "user-avatar" %>
        </div>
      </div>
      <div>
        <div class="font-bold"><%= user.username %></div>
        <div class="text-sm opacity-50"><%= user.full_name %></div>
      </div>
    </div>
  </td>
  <td>
    <%= user.email %>
    <br />
    <span class="badge badge-ghost badge-sm"><%=  user.phone %></span>
  </td>
  <td>
    <%= user.role.capitalize %>
    <br>
    <span class="badge badge-primary p-2 rounded-lg badge-sm"><%= user.status.capitalize %></span>
  </td>
  <th>
    <%= link_to "details", [:admin, user], class: "btn btn-ghost btn-md text-xs" %>
  </th>
</tr>

app/views/admin/users/_users_table.html.erb
<table class="table">
  <!-- head -->
  <thead>
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th>Status</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% users.each do |user| %>

    <%= render partial: "admin/users/user_row", locals: { user: user } %>

  <% end %>
  </tbody>
  <!-- foot -->
  <tfoot>
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th>Status</th>
    <th></th>
  </tr>
  </tfoot>
</table>

app/views/admin/users/edit.html.erb
<% content_for :title, "Updating User" %>

<section class="w-full">
  <header class="flex justify-between">
    <h1 class="font-bold text-4xl">
      <i class="fa-solid fa-user-pen pr-2"></i>
      Editing user
    </h1>
    <%= link_to admin_users_path, class: "btn btn-ghost" do %>
      <i class="fas fa-arrow-left"></i> Back to users
    <% end %>
  </header>

  <%= link_to [:admin, @user], class: "btn btn-ghost mx-auto pl-0 hover:bg-transparent" do %>
    Show this user
    <i class="fas fa-eye text-xl"></i>
  <% end %>
  <article class="max-w-lg mx-auto">
    <%= render "form", user: @user %>
  </article>

</section>

app/views/admin/users/index.html.erb
<section class="w-full mx-auto">
  <% content_for :title, "Users" %>

  <header class="flex justify-between">
    <h1 class="font-bold text-4xl">
      <i class="fas fa-users px-2"></i>
      Users
    </h1>
    <%= link_to new_admin_user_path, class: "btn btn-outline rounded-lg py-3 px-5" do %>
      <i class="fas fa-plus"></i> Add User
    <% end %>
    </header>

  <article id="users-stats" class="flex justify-between items-center max-w-screen-2xl py-4 ">
    <div class="stats stats-vertical sm:stats-horizontal mx-auto shadow w-full">
      <div class="stat place-items-center">
        <div class="stat-title">Total users</div>
        <%= render 'shared/animated_number',
                   message: @total_users_count,
                   start_value: 0,
                   end_value: @total_users_count,
                   classes: "stat-value"
        %>
        <div class="stat-desc">All time</div>
      </div>

      <div class="stat place-items-center">
        <div class="stat-title">Active Users</div>
        <%= render 'shared/animated_number',
                   message: @total_users_active,
                   start_value: 0,
                   end_value: @total_users_active,
                   classes: "stat-value"
        %>
        <div class="stat-desc"></div>
      </div>

      <div class="stat place-items-center">
        <div class="stat-title">New Users</div>
        <%= render 'shared/animated_number',
                   message: @total_users_last_month,
                   start_value: 0,
                   end_value: @total_users_last_month,
                   classes: "stat-value"
        %>
        <div class="stat-desc">Last month</div>
      </div>
    </div>
  </article>

  <article id="users" class="max-w-screen-xl mx-auto mt-4">
    <%= form_tag admin_users_path, method: :get, class: "flex flex-col md:flex-row gap-3 items-center justify-center py-2" do %>
      <%= text_field_tag :query,
                         params[:query],
                         placeholder: "Search users...",
                         class: "input input-bordered w-full" %>
      <%= select_tag :status, options_for_select(User.statuses.keys.map { |status| [status.titleize, status] }),
                     class: 'select select-bordered  max-w-xs' %>

      <%= submit_tag "Search",
                     class: "btn btn-outline w-full lg:btn-wide" %>

      <%= link_to "Reset",
                  admin_users_path,
                  class: "btn btn-ghost join-item" %>
    <% end %>

    <div class="overflow-x-auto flex flex-col justify-center items-center pt-4">

      <%== pagy_nav(@pagy) %>

      <%= render partial: "users_table", locals: { users: @users }%>

      <%== pagy_nav(@pagy) %>

    </div>
  </article>
</section>

app/views/admin/users/new.html.erb
<% content_for :title, "Adding User" %>

<section class="w-full">
  <header class="flex justify-between">
    <h1 class="font-bold text-4xl">
      <i class="fa-solid fa-user-plus pr-2"></i>
      New user</h1>
    <%= link_to admin_users_path, class: "btn btn-ghost" do %>
      <i class="fas fa-arrow-left"></i> Back to users
    <% end %>
  </header>

  <article class="max-w-lg mx-auto">
    <%= render "form", user: @user %>
  </article>

</section>

app/views/admin/users/show.html.erb
<% content_for :title, "Showing User" %>

<section class="flex flex-col gap-4 mx-auto">
  <header class="flex justify-between">
    <h1 class="font-bold text-xl md:text-4xl">
      <i class="fas fa-eye pr-2"></i>
      Showing: <%= @user.username %></h1>
    <%= link_to admin_users_path, class: "btn btn-ghost" do %>
      <i class="fas fa-arrow-left"></i> Back to users
    <% end %>
  </header>

  <article id="actions">
    <details class="collapse bg-base-100 collapse-arrow border-2 border-base-300 rounded-lg shadow-md">
      <summary class="collapse-title font-medium">
        <i class="fa-solid fa-wand-magic-sparkles mr-1 text-xl"></i>
        Actions
      </summary>
      <div class="collapse-content">
        <div class="flex flex-wrap gap-2 justify-evenly">
          <%#= button_to [:admin, @user], method: :delete, class: "btn btn-outline btn-lg lg:btn-wide" do %>
<!--            <i class="fas fa-trash-alt"></i> Destroy-->
          <%# end %>
          <% if @user.active_status? || @user.inactive_status? %>
            <%= button_to block_admin_user_path(@user), method: :post, class: "btn btn-outline btn-lg lg:btn-wide" do %>
              <i class="fas fa-ban"></i>
              Block
            <% end %>
          <% elsif @user.blocked_status? %>
            <%= button_to activate_admin_user_path(@user), method: :post, class: "btn btn-outline btn-lg lg:btn-wide" do %>
              <i class="fas fa-check-circle"></i>
              Activate
            <% end %>
          <% end %>

          <%= link_to edit_admin_user_path(@user), class: "btn btn-outline btn-lg lg:btn-wide" do %>
            <i class="fas fa-edit"></i> Update
          <% end %>
        </div>
      </div>
    </details>
  </article>

  <section id="user-information" class="flex justify-center mt-4">
    <div class="card indicator md:card-side bg-base-100 shadow-xl">
      <span class="indicator-item indicator-top indicator-center badge badge-lg badge-primary p-6 text-xl font-bold rounded-lg">
        <%= @user.status.capitalize %>
      </span>
      <figure class="max-w-[300px]">
        <%= image_tag avatar_url(@user), 
          alt: "#{current_user&.username}'s avatar", 
          class: "user-avatar" %>
      </figure>
      <div class="card-body">
        <%= render @user %>
      </div>
    </div>

  </section>
</section>